services:
  marzban:
    image: gozargah/marzban:latest
    restart: always
    env_file: .env
    network_mode: host
    ports:
      - '9000:8000'
    volumes:
      - /var/lib/marzban:/var/lib/marzban
